import {
  isTrim,
  snackBar,
  dimen_size_height,
  dimen_size_width,
  isResponseValid,
  validateEmail,
  passWordValidation,
  allowOnlyLetter,
  allowNumOnly,
  numericOnly,
  validURL,
  allowFloatDigitOnly,
  isIphoneX,
  getStatusBarHeight,
  getBottomSpace,
} from "./helpers";
export {
  dimen_size_height,
  dimen_size_width,
  isTrim,
  snackBar,
  isResponseValid,
  validateEmail,
  passWordValidation,
  allowOnlyLetter,
  allowNumOnly,
  numericOnly,
  validURL,
  allowFloatDigitOnly,
  isIphoneX,
  getStatusBarHeight,
  getBottomSpace
};
